# Generated by Django 3.2.6 on 2021-09-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='puntos_total',
            field=models.IntegerField(null=True),
        ),
    ]
