# Generated by Django 3.2.6 on 2021-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuarios_puntos_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='puntos_total',
            field=models.IntegerField(default=0),
        ),
    ]
