# Generated by Django 3.2.6 on 2021-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_correcta', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'jugar',
            },
        ),
    ]
