# Generated by Django 3.2.6 on 2021-09-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(choices=[('1', 'ACTIVO'), ('0', 'INACTIVO')], max_length=255, null=True)),
                ('cargar_pregunta', models.ManyToManyField(related_name='cargar_pregunta', to='preguntas.cargar_pregunta')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.categoria')),
            ],
            options={
                'db_table': 'jugar',
            },
        ),
    ]
