# Generated by Django 3.2.6 on 2021-09-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugar',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='jugar',
            name='puntaje',
        ),
    ]
