# Generated by Django 3.2.6 on 2021-08-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_alter_respuesta_correcta_table'),
        ('jugar_preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugar',
            name='respuesta_correcta',
        ),
        migrations.AddField(
            model_name='jugar',
            name='respuesta_incorrecta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.respuesta_incorrecta'),
        ),
    ]
