# Generated by Django 3.2.6 on 2021-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugar',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('0', 'INACTIVO')], max_length=255, null=True),
        ),
    ]
