# Generated by Django 3.2.6 on 2021-08-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0002_auto_20210826_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugar',
            old_name='respuesta_incorrecta',
            new_name='incorrecta',
        ),
    ]
