# Generated by Django 3.2.6 on 2021-08-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0003_rename_respuesta_incorrecta_jugar_incorrecta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugar',
            old_name='incorrecta',
            new_name='respuesta_incorrecta',
        ),
    ]
