# Generated by Django 3.2.6 on 2021-08-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0004_rename_incorrecta_jugar_respuesta_incorrecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugar',
            name='puntage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
