# Generated by Django 3.2.6 on 2021-08-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_auto_20210827_0342'),
        ('jugar_preguntas', '0005_jugar_puntage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugar',
            old_name='puntage',
            new_name='puntaje',
        ),
        migrations.RemoveField(
            model_name='jugar',
            name='respuesta_incorrecta',
        ),
        migrations.AddField(
            model_name='jugar',
            name='cargar_pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.cargar_pregunta'),
        ),
    ]
