# Generated by Django 3.2.6 on 2021-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20210828_0357'),
        ('jugar_preguntas', '0006_auto_20210827_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugar',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria', to='preguntas.categoria'),
        ),
        migrations.AddField(
            model_name='jugar',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
