# Generated by Django 3.2.6 on 2021-08-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_auto_20210828_0410'),
        ('jugar_preguntas', '0007_auto_20210828_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugar',
            name='cargar_pregunta',
        ),
        migrations.AddField(
            model_name='jugar',
            name='cargar_pregunta',
            field=models.ManyToManyField(related_name='cargar_pregunta', to='preguntas.cargar_pregunta'),
        ),
        migrations.RemoveField(
            model_name='jugar',
            name='categoria',
        ),
        migrations.AddField(
            model_name='jugar',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.categoria'),
        ),
    ]
