# Generated by Django 3.2.6 on 2021-08-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0008_auto_20210828_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugar',
            name='categoria',
        ),
    ]
