# Generated by Django 3.2.6 on 2021-08-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0009_remove_jugar_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jugar',
        ),
    ]
