# Generated by Django 3.2.6 on 2021-09-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugar_preguntas', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feche_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('Puntuacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'gano'), ('0', 'perdio')], max_length=6)),
                ('nivel', models.IntegerField()),
                ('juegos', models.ManyToManyField(to='jugar_preguntas.jugar')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.jugadore')),
            ],
            options={
                'db_table': 'estadisticas',
            },
        ),
    ]
