# Generated by Django 3.2.6 on 2021-09-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticas',
            name='Puntuacion',
        ),
        migrations.RemoveField(
            model_name='estadisticas',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='estadisticas',
            name='feche_ingreso',
        ),
        migrations.RemoveField(
            model_name='estadisticas',
            name='nivel',
        ),
    ]
