# Generated by Django 3.2.6 on 2021-09-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugar_preguntas', '0002_auto_20210902_0735'),
        ('estadisticas', '0002_auto_20210902_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='opcion',
            field=models.CharField(choices=[('0', 'opcion1'), ('1', 'opcion2')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='estadisticas',
            name='estado',
            field=models.CharField(choices=[('1', 'gano'), ('0', 'perdio')], default=0, max_length=6),
        ),
        migrations.RemoveField(
            model_name='estadisticas',
            name='juegos',
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='juegos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jugar_preguntas.jugar'),
        ),
    ]
