# Generated by Django 3.2.6 on 2021-09-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_auto_20210904_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticas',
            name='opcion',
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estadisticas',
            name='estado',
            field=models.CharField(choices=[('1', 'gano'), ('0', 'perdio')], max_length=2, null=True),
        ),
    ]
