# Generated by Django 3.2.6 on 2021-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0004_auto_20210904_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='nivel',
            field=models.IntegerField(null=True),
        ),
    ]
