# Generated by Django 3.2.6 on 2021-09-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0005_estadisticas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='puntos_total',
            field=models.IntegerField(null=True),
        ),
    ]
