# Generated by Django 3.2.6 on 2021-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jugadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'jugadores',
            },
        ),
    ]
