# Generated by Django 3.2.6 on 2021-08-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_auto_20210825_2116'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jugadores',
            table='jugadore',
        ),
    ]
