# Generated by Django 3.2.6 on 2021-08-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_alter_jugadores_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jugadores',
            table='jugadores',
        ),
    ]
