# Generated by Django 3.2.6 on 2021-08-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_alter_jugadores_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jugadores',
            new_name='jugadore',
        ),
    ]
