# Generated by Django 3.2.6 on 2021-08-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargar_pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='respuesta_correcta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.cargar_pregunta')),
            ],
            options={
                'db_table': 'respuestas_incorrecta',
            },
        ),
        migrations.CreateModel(
            name='respuesta_incorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_incorrecta', models.CharField(max_length=255)),
                ('respuesta_correcta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.respuesta_correcta')),
            ],
            options={
                'db_table': 'respuesta_incorrecta',
            },
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.categoria'),
        ),
    ]
