# Generated by Django 3.2.6 on 2021-08-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='respuesta_correcta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'respuesta_correcta',
            },
        ),
        migrations.CreateModel(
            name='respuesta_incorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrecta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'respuesta_incorrecta',
            },
        ),
        migrations.CreateModel(
            name='cargar_pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.categoria')),
                ('respuesta_correcta', models.ManyToManyField(to='preguntas.respuesta_correcta')),
                ('respuesta_incorrecta', models.ManyToManyField(to='preguntas.respuesta_incorrecta')),
            ],
            options={
                'db_table': 'cargar_pregunta',
            },
        ),
    ]
