# Generated by Django 3.2.6 on 2021-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargar_pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='cargar_respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('respuesta1', models.CharField(max_length=255)),
                ('respuesta2', models.CharField(max_length=255)),
                ('respuesta3', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
    ]
