# Generated by Django 3.2.6 on 2021-08-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='respuesta_correcta',
            table='respuestas_correcta',
        ),
    ]
