# Generated by Django 3.2.6 on 2021-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='preguntas.categoria'),
        ),
        migrations.AlterField(
            model_name='cargar_pregunta',
            name='respuesta_correcta',
            field=models.ManyToManyField(related_name='respuesta_correctas', to='preguntas.respuesta_correcta'),
        ),
        migrations.AlterField(
            model_name='cargar_pregunta',
            name='respuesta_incorrecta',
            field=models.ManyToManyField(related_name='respuesta_incorrectas', to='preguntas.respuesta_incorrecta'),
        ),
    ]
