# Generated by Django 3.2.6 on 2021-08-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_alter_respuesta_correcta_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='respuesta_correcta',
            table='respuesta_correcta',
        ),
    ]
