# Generated by Django 3.2.6 on 2021-08-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_alter_respuesta_correcta_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='categorias',
            field=models.ManyToManyField(related_name='categoria', to='preguntas.categoria'),
        ),
    ]
