# Generated by Django 3.2.6 on 2021-09-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_respuesta_incorrecta_correcta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='respuesta_correcta',
        ),
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='respuesta_incorrecta',
        ),
        migrations.RemoveField(
            model_name='respuesta_incorrecta',
            name='correcta',
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctas', models.ManyToManyField(null=True, related_name='respuesta_correctas', to='preguntas.respuesta_correcta')),
                ('incorrectas', models.ManyToManyField(null=True, related_name='respuesta_correctas', to='preguntas.respuesta_incorrecta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.respuesta'),
        ),
    ]
