# Generated by Django 3.2.6 on 2021-08-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20210827_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargar_pregunta',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
