# Generated by Django 3.2.6 on 2021-09-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_auto_20210907_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='respuesta',
            field=models.ManyToManyField(null=True, related_name='respuestas', to='preguntas.respuesta'),
        ),
    ]
