# Generated by Django 3.2.6 on 2021-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_rename_categorias_cargar_pregunta_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_incorrecta',
            name='respuesta_correcta',
        ),
        migrations.AddField(
            model_name='respuesta_incorrecta',
            name='respuesta_correcta',
            field=models.ManyToManyField(related_name='respuesta_correctas', to='preguntas.respuesta_correcta'),
        ),
    ]
