# Generated by Django 3.2.6 on 2021-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_auto_20210827_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_correcta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta_incorrecta',
            name='respuesta_correcta',
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='respuesta_correcta',
            field=models.ManyToManyField(related_name='respuesta_correctas', to='preguntas.respuesta_correcta'),
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='respuesta_incorrecta',
            field=models.ManyToManyField(related_name='respuesta_incorrectas', to='preguntas.respuesta_incorrecta'),
        ),
    ]
