# Generated by Django 3.2.6 on 2021-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20210828_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar_pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cargar_pregunta',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria', to='preguntas.categoria'),
        ),
    ]
