# Generated by Django 3.2.6 on 2021-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_auto_20210828_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargar_pregunta',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='preguntas.categoria'),
        ),
    ]
